### PR TITLE
Added links for newly uploaded videos

### PR DESCRIPTION
**Pull request by robertu94**
Added links

### CODE REVIEW

**Comment by ProtractorNinja** [comment]
Only one new link is intentional, right?

**Comment by robertu94** [comment]
Only one was replaced, the rest were entirely new links

**Comment by ProtractorNinja** [comment]
So it's intentional that this pull request only updates one link, then?

**Comment by ProtractorNinja** [comment]
Never mind, I am dumb.

**Comment by robertu94** [comment]
I assume we can merge this now?

**Pull request merged**
